In [1]:
from transformers import DPRQuestionEncoder, DPRQuestionEncoderTokenizer, DPRContextEncoder, DPRContextEncoderTokenizer
import torch

In [4]:
chkp = "crystina-z/mdpr-tied-msmarco-pyserini"

In [5]:
model_question = DPRQuestionEncoder.from_pretrained(chkp)
model_context = DPRContextEncoder.from_pretrained(chkp)
tokenizer_context = DPRContextEncoderTokenizer.from_pretrained(chkp)
tokenizer_question = DPRQuestionEncoderTokenizer.from_pretrained(chkp)

config.json:   0%|          | 0.00/891 [00:00<?, ?B/s]

You are using a model of type bert to instantiate a model of type dpr. This is not supported for all configurations of models and can yield errors.


pytorch_model.bin:   0%|          | 0.00/711M [00:00<?, ?B/s]

You are using a model of type bert to instantiate a model of type dpr. This is not supported for all configurations of models and can yield errors.


tokenizer_config.json:   0%|          | 0.00/407 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'BertTokenizer'. 
The class this function is called from is 'DPRContextEncoderTokenizer'.
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'BertTokenizer'. 
The class this function is called from is 'DPRQuestionEncoderTokenizer'.


In [7]:
sim = torch.nn.CosineSimilarity(dim=1, eps=1e-6)

In [9]:
def get_q_vec(sent, tokenizer, model):
    input_ids = tokenizer(sent, return_tensors="pt")["input_ids"]
    embeddings = model(input_ids).pooler_output
    return embeddings

In [8]:
question = 'อยุธยามีกี่อำเภอ ?'
context_1 = 'ละครครั้งที่ 3'
context_2 = 'ปัจจุบันจังหวัดพระนครศรีอยุธยาประกอบด้วย 16 อำเภอ ได้แก่'

In [11]:
emb_q = get_q_vec(question, tokenizer_question, model_question)
print(emb_q.shape)
emb_q

torch.Size([1, 768])


tensor([[ 3.6405e-02, -7.3953e-02,  6.2699e-01, -1.4832e-01,  2.4013e-01,
          3.3051e-02,  1.6314e-02,  9.7362e-02, -1.3794e-01,  2.4226e-01,
         -3.4246e-01,  2.8867e-01, -8.0519e-02,  4.1817e-01,  3.0458e-01,
          3.6929e-01,  3.6280e-02, -9.1029e-02,  2.3724e-02, -7.7715e-02,
          1.7783e-01,  1.3786e-01, -1.6628e-01,  4.4453e-02, -1.8796e-01,
          9.6551e-01,  2.8754e-01,  1.7689e-01, -3.2657e-03, -1.5062e-01,
          7.6656e-02,  1.7254e-01, -8.2568e-02,  3.6658e-01, -1.2656e-01,
         -1.3417e-01,  2.0889e-01,  5.4881e-01,  1.6555e-01, -1.5862e-01,
         -1.0520e-01, -2.2546e-01, -1.0918e-01, -1.7329e-02,  5.5634e-02,
          2.7986e-01,  2.8422e-01, -2.6420e-01,  1.2300e-02,  1.0689e+00,
          1.8546e-02,  1.8566e-01,  4.8382e-03, -2.6558e-01,  1.9138e-01,
          5.6418e-01, -5.9635e-01,  3.6975e-01,  3.4857e-01,  2.1061e-01,
         -2.5530e-01, -4.2127e-01,  5.9402e-01, -2.4738e-01, -3.7408e-01,
          7.9038e-03, -1.7161e-01,  1.

In [13]:
emb_c1 = get_q_vec(context_1, tokenizer_context, model_context)
print(emb_c1.shape)
emb_c1

torch.Size([1, 768])


tensor([[ 4.9960e-02, -2.3169e-01,  3.5681e-01, -6.5786e-02,  1.4863e-01,
         -3.3583e-02, -2.8397e-02, -1.4630e-01,  2.6505e-02,  3.9342e-01,
         -5.4954e-01,  2.5044e-02, -1.5532e-01,  4.9291e-01,  6.4636e-02,
         -1.8772e-04,  5.0649e-01, -7.3415e-02,  2.4486e-01,  2.9466e-01,
         -6.4955e-01, -1.4817e-01,  2.0940e-01, -5.7210e-02, -7.4595e-02,
          7.7132e-01, -7.7784e-02, -3.3264e-02,  5.3535e-01, -2.4244e-01,
         -6.7971e-02,  2.2578e-02, -2.4475e-01,  1.0397e-01,  8.3125e-02,
         -1.0019e-01, -8.6823e-02,  3.0079e-01, -1.3796e-01,  3.1029e-01,
         -9.5102e-02, -3.9509e-01, -2.6858e-02, -1.4825e-01, -9.6022e-02,
         -1.7389e-01,  1.4829e-01,  6.4744e-01, -1.7815e-01,  3.4631e-01,
         -3.2797e-01,  2.9323e-01, -1.3760e-01, -2.6676e-01,  4.2241e-01,
          6.8699e-01,  6.7793e-02,  5.7139e-01,  7.2163e-02, -1.2861e-01,
         -2.8198e-01, -2.0984e-01, -3.0984e-01, -1.7546e-01, -3.3074e-02,
          5.1631e-03,  1.6553e-01, -4.

In [14]:
emb_c2 = get_q_vec(context_2, tokenizer_context, model_context)
print(emb_c2.shape)
emb_c2

torch.Size([1, 768])


tensor([[-3.0286e-02, -5.1119e-03,  6.1054e-01, -2.9515e-01,  1.9539e-01,
         -1.5823e-01, -1.0115e-01,  7.8038e-03, -7.2004e-02,  2.6102e-01,
         -4.6435e-01,  5.3285e-02, -1.0280e-02,  2.9917e-01,  2.9851e-01,
          6.8015e-02,  1.1876e-01, -7.5998e-02, -3.3398e-03,  6.5068e-01,
          2.2972e-01, -9.3091e-02, -4.0131e-01, -6.0300e-02,  1.4439e-01,
          2.7379e-01,  3.0980e-01,  1.1450e-01, -2.9877e-01, -2.2408e-01,
         -6.9720e-02,  1.8125e-01, -3.9436e-01,  3.6534e-01, -1.2880e-01,
          7.8554e-02,  3.6061e-01,  5.6324e-01,  8.7328e-02,  4.1904e-02,
          1.2454e-01,  6.5037e-02, -1.7371e-01,  4.2979e-02,  1.3377e-01,
          4.2478e-01,  1.7464e-01,  2.4715e-02,  1.9589e-01,  7.5089e-01,
         -2.6279e-01,  3.6788e-01,  1.6540e-01,  1.4161e-01,  3.9344e-02,
          5.1573e-02, -3.8984e-01,  5.8001e-01,  4.8357e-01,  4.2938e-01,
          1.8170e-01, -3.6953e-01,  1.3958e-01, -3.2111e-01, -1.2439e-01,
         -7.6449e-02, -1.5753e-01, -1.

In [15]:
sim(emb_q, emb_c1)

tensor([0.5470], grad_fn=<SumBackward1>)

In [16]:
sim(emb_q, emb_c2)

tensor([0.7449], grad_fn=<SumBackward1>)